name = "NyquistCircuitModeling"
uuid = "f3ad492f-9a84-4543-9158-2c657cfb626e"
authors = ["Ir1n-a <159860234+Ir1n-a@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10"
NativeFileDialog = "0.2"
Plots = "1"
Optimization = "3"
StatsBase = "0.34"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
